# Generated by Django 4.1.2 on 2022-10-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonika', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
