# Generated by Django 4.1.2 on 2022-12-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonika', '0003_remove_user_login_user_groups_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
